apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-secret
  namespace: production # change the namespace
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ecr-rbac
subjects:
  - kind: ServiceAccount
    name: ecr-secret
    namespace: production # change the namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io